behaviors:
  Arah:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 4.0e-5
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 20000000
    time_horizon: 512
    summary_freq: 1000